name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  
  audioplayers: ^0.20.1
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_cmoon_icons: ^0.1.0
  just_audio: ^0.9.13
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  
